version: 2
jobs:
  build:
    working_directory: ~/record
    docker:
      - image: crystallang/crystal:0.23.1
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: lucky-record
          POSTGRES_DB: lucky_record_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: crystal deps
      - run: lucky db.migrate
      - run: crystal spec
